import type { zApplication } from "@/src/types/db";
import dayjs from "dayjs";

export const needToApplyMocks: zApplication["GET"][] = [
	{
		id: 1,
		position: "Marketing Manager",
		company: {
			id: 0,
			name: "Coca-Cola",
			contacts: [],
			contactIds: [],
		},
		companyId: 0,
		status: "Need To Apply",
		contacts: [],
		notes: [],
		dateCreated: dayjs().toISOString(),
		dateModified: "2023-06-13T06:00:00.000Z",
		cardColor: "#1C90BF",
		location: "In-person",
		submission: "Job Fair",
		jobType: "Full-time",
	},
	{
		id: 2,
		position: "Project Coordinator",
		company: {
			id: 0,
			name: "UNICEF",
			contacts: [],
			contactIds: [],
		},
		companyId: 0,
		status: "Need To Apply",
		contacts: [],
		notes: [],
		dateCreated: dayjs().subtract(1, "week").toISOString(),
		dateModified: "2023-08-28T06:00:00.000Z",
		cardColor: "#30C5D2",
		location: "Hybrid",
		submission: "Job Fair",
		jobType: "Internship",
	},
	{
		id: 3,
		position: "Data Engineer",
		company: {
			id: 0,
			name: "Daylight Solutions",
			contacts: [],
			contactIds: [],
		},
		companyId: 0,
		status: "Need To Apply",
		contacts: [],
		notes: [],
		dateCreated: dayjs().subtract(3, "week").toISOString(),
		dateModified: "2023-11-12T20:00:00.000Z",
		cardColor: "#6EF195",
		location: "Remote",
		submission: "Recruitment Agency",
		jobType: "Part-time",
		customFields: [{ label: "Recruiter Name", value: "Jason Jackson" }],
	},
	{
		id: 5,
		position: "Senior Data Analyst",
		company: {
			id: 0,
			name: "Acme Inc.",
			contacts: [],
			contactIds: [],
		},
		companyId: 0,
		status: "Need To Apply",
		contacts: [],
		notes: [],
		dateCreated: dayjs().subtract(1.5, "month").toISOString(),
		dateModified: "2023-10-12T20:00:00.000Z",
		cardColor: "#FCB0F3",
		location: "Hybrid",
		submission: "Email",
		jobType: "Freelance",
		wage: {
			payType: "Hourly",
			rate: 22,
		},
	},
	{
		id: 4,
		position: "Project Manager",
		company: {
			id: 0,
			name: "Mason Consulting",
			contacts: [],
			contactIds: [],
		},
		companyId: 0,
		status: "Need To Apply",
		contacts: [],
		notes: [],
		dateCreated: dayjs().subtract(3, "month").toISOString(),
		dateModified: "2023-10-12T20:00:00.000Z",
		cardColor: "#1A2766",
		location: "Hybrid",
		submission: "Online",
		jobType: "Full-time",
		wage: {
			payType: "Salary",
			annualSalary: 75000,
		},
	},
];

export const offerMocks: zApplication["GET"][] = [
	{
		id: 11,
		position: "Sales Representative",
		company: {
			id: 0,
			name: "Apple",
			contacts: [],
			contactIds: [],
		},
		companyId: 0,
		status: "Offer",
		contacts: [],
		notes: [],
		dateCreated: dayjs().subtract(1, "week").toISOString(),
		dateModified: "2023-11-07T06:00:00.000Z",
		dateApplied: "2023-11-09T04:00:00.000Z",
		dateInterviewing: "2023-11-11T04:00:00.000Z",
		dateOffered: "2023-11-13T04:00:00.000Z",
		cardColor: "#FCB0F3",
		location: "Remote",
		submission: "Other",
		jobType: "Contract",
		wage: {
			payType: "Contract",
			duration: "1 year",
			totalAmount: 40000,
		},
	},
	{
		id: 10,
		position: "Human Resources Specialist",
		company: {
			id: 0,
			name: "Amazon",
			contacts: [],
			contactIds: [],
		},
		companyId: 0,
		status: "Offer",
		contacts: [],
		notes: [],
		dateCreated: dayjs().subtract(1, "month").toISOString(),
		dateModified: "2023-10-04T06:00:00.000Z",
		dateApplied: "2023-10-06T04:00:00.000Z",
		dateInterviewing: "2023-10-08T04:00:00.000Z",
		dateOffered: "2023-10-10T04:00:00.000Z",
		cardColor: "#F8997D",
		location: "In-person",
		submission: "Referral",
		jobType: "Freelance",
		customFields: [{ label: "Commission", value: "400 per contract" }],
	},
];
